name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Set up Environment Variables
        run: |
          echo "SERVER_HOSTNAME=${{ secrets.SQL_SERVER_HOST }}" >> $GITHUB_ENV
          echo "HTTP_PATH=${{ secrets.SQL_HTTP }}" >> $GITHUB_ENV
          echo "ACCESS_TOKEN=${{ secrets.DATABRICKS_API_KEY }}" >> $GITHUB_ENV
      - name: install packages
        run: make install
      - name: lint
        run: make lint
      - name: extract 
        run: make extract 
      - name: transform_load
        run: make transform_load 
      - name: query
        run: make query
      - name: test
        run: make test
      - name: format
        run: make format
      - name: deploy
        run: make deploy